# Generated by Django 4.0.1 on 2022-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='DefaultSubtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='DefaultTheme', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='DefaultTitle', max_length=50),
        ),
    ]
