# Generated by Django 4.0.1 on 2022-01-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_content_alter_blog_subtitle_alter_blog_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
