# Generated by Django 4.0.1 on 2022-01-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
