# Generated by Django 4.0.1 on 2022-01-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.TextField(default=''),
        ),
    ]
